# fly.toml app configuration file generated for hoc33 on 2023-05-28T11:49:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hoc33"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
